### PR TITLE
renamed NewCardForm.js with capital N

### PR DESCRIPTION
**Pull request by JohnDHamm**
had issue with path since filename didn't begin with a capital "N"...to be honest, I also needed the practice of working with a forked project and doing a pull request. Hence the simple PR!

### CODE REVIEW

**Review by TannerPlauche — COMMENTED** [review]
I am not familiar with some of these node modules.  Do you intend to use the new modules?

**Comment by JohnDHamm** [comment]
Sorry, I have no idea where they came from. I ran npm install but did not try to add any other modules.

**Comment by JohnDHamm** [comment]
Feel free to disregard this PR and I will re-pull dev.

**Comment by TannerPlauche** [comment]
Rejecting this PR. No need to add those changes yet.

**Pull request closed without merging**
